from zen_garden.model.component_types.parameter import GenericParameter


class BackupPotential(GenericParameter):
    """Energy that can be generated by backup power plants during winter."""

    name = "backup_potential"
    indices = ("set_carriers", "set_nodes", "set_years")
    doc = "Potential backup generation available during winter"
    unit_category = {"energy_quantity": 1}
    time_series = False
    default_value = 0
    default_unit = "availability_import_yearly"
